account/urls.py
from django.urls import path

from account.views import (
    account_view,
    edit_account_view,
    crop_image,
)

app_name = 'account'

urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit', edit_account_view, name="edit"),
    path('<user_id>/edit/cropImage/', crop_image, name="crop_image"),
]

chat/urls.py
from django.urls import path

from chat.views import (
    private_chat_room_view,
    create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
    path('', private_chat_room_view, name='private-chat-room'),
    path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

chat_django/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from personal.views import (
    home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,

)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('search/', account_search_view, name="search"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/base_css.html
<style type="text/css">
    head{
        font-family: "Segoe UI";
        font-weight: 380;
    }
    footer{
        font-family: "Segoe UI";
        font-weight: 380;
    }
    body{
        background-color: #f2f2f2;
        font-family: "Segoe UI";
        font-weight: 380;
    }

    :root{
        --main-background-color: #f2f2f2;
        --dark-background-color: #a2a2a2;
        --secondary-text-color: #808080;
        --light-primary-text-color: #0080ff;
    }
    
    


</style>

templates/snippets/base_js.html
<script type="text/javascript">

    function preloadCallback(src, elementId) {
        var img = document.getElementById(elementId)
        img.src = src
    }

    function preloadImage(imgSrc, elementId) {
        // console.log("attempting to load " + imgSrc + " on element " + elementId)
        var objImagePreloader = new Image();
        objImagePreloader.src = imgSrc;
        if (objImagePreloader.complete) {
            preloadCallback(objImagePreloader.src, elementId);
            objImagePreloader.onload = function () {
            };
        } else {
            objImagePreloader.onload = function () {
                preloadCallback(objImagePreloader.src, elementId);
                //    clear onLoad, IE behaves irratically with animated gifs otherwise
                objImagePreloader.onload = function () {
                };
            }
        }
    }

    /*
        Build a <p> for messages using markdown
        https://github.com/markdown-it/markdown-it
    */
    function validateText(str) {
        var md = window.markdownit({
            highlight: function (str, lang) {
                if (lang && hljs.getLanguage(lang)) {
                    try {
                        return '<pre class="hljs"><code>' +
                            hljs.highlight(lang, str, true).value +
                            '</code></pre>';
                    } catch (__) {
                    }
                }
                return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
            },
            linkify: true,
        });
        var result = md.render(str);
        return result
    }

</script>

templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 100px;
    }
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
    <p class="m-auto">Codingwithmitch Chat | 2020</p>
</div>
<!-- End Footer -->

templates/snippets/general_notifications.html
{% load static %}


<style type="text/css">
	.notification-thumbnail-image{
		height: 50px;
		width: 50px;
	}
	.general-card:hover{
		cursor: pointer;
		background: #f2f2f2;
	}
	.general-card{
		border-bottom: 1px solid var(--main-background-color);
	}
	.timestamp-text{
		color: var(--secondary-text-color);
	}

	#id_notifications_loading_spinner{
		position: absolute;
		margin-top: 40px;
	}
</style>


<script src="{% static 'collections/collections.min.js' %}"></script>

<script type="text/javascript">

	/*
		Received a payload from socket containing notifications.
		Called:
			1. When page loads
			2. pagination
	*/
	function handleGeneralNotificationsData(notifications, new_page_number){
		if(notifications.length > 0){
			clearNoGeneralNotificationsCard()
			notifications.forEach(notification => {

				appendBottomGeneralNotification(notification)

			})
		}
	}

	/*
		Append a general notification to the BOTTOM of the list.
	*/
	function appendBottomGeneralNotification(notification){

		switch(notification['notification_type']) {

			case "FriendRequest":
				notificationContainer = document.getElementById("id_general_notifications_container")
				card = createFriendRequestElement(notification)
				notificationContainer.appendChild(card)
				break;

			case "FriendList":
				notificationContainer = document.getElementById("id_general_notifications_container")
				card = createFriendListElement(notification)
				notificationContainer.appendChild(card)
				break;

			default:
				// code block
		}
		preloadImage(notification['from']['image_url'], assignGeneralImgId(notification))
	}

	function createFriendListElement(notification){
		card = createGeneralNotificationCard()
		card.id = assignGeneralCardId(notification)
		card.addEventListener("click", function(){
			generalRedirect(notification['actions']['redirect_url'])
		})

		var div1 = document.createElement("div")
		div1.classList.add("d-flex", "flex-row", "align-items-start")
		div1.id = assignGeneralDiv1Id(notification)

		img = createGeneralProfileImageThumbnail(notification)
		div1.appendChild(img)

		span = document.createElement("span")
		span.classList.add("align-items-start", "pt-1", "m-auto")
		if(notification['verb'].length > 50){
			span.innerHTML = notification['verb'].slice(0, 50) + "..."
		}
		else{
			span.innerHTML = notification['verb']
		}
		span.id = assignGeneralVerbId(notification)
		div1.appendChild(span)
		card.appendChild(div1)
		card.appendChild(createGeneralTimestampElement(notification))

		return card
	}

	/*
		Create a Notification Card for a FriendRequest payload
		Ex: "John sent you a friend request."
		Ex: "You declined John's friend request."
		Ex: "You accepted John's friend request."
		Ex: "You cancelled the friend request to Kiba."
		Ex: "Maizy accepted your friend request."
		Ex: "Maizy declined your friend request."
		Params:
			1. redirect_url
				- Will redirect to the other users profile
	*/
	function createFriendRequestElement(notification){
		card = createGeneralNotificationCard()

		// assign id b/c we need to find this div if they accept/decline the friend request
		card.id = assignGeneralCardId(notification)
		card.addEventListener("click", function(){
			generalRedirect(notification['actions']['redirect_url'])
		})

		// Is the friend request PENDING? (not answered yet)
		if(notification['is_active'] == "True"){

			//console.log("found an active friend request")
			div1 = document.createElement("div")
			div1.classList.add("d-flex", "flex-row", "align-items-start")
			div1.id = assignGeneralDiv1Id(notification)

			img = createGeneralProfileImageThumbnail(notification)
			div1.appendChild(img)

			span = document.createElement("span")
			span.classList.add("m-auto")
			span.innerHTML = notification['verb']
			span.id = assignGeneralVerbId(notification)
			div1.appendChild(span)
			card.appendChild(div1)

			div2 = document.createElement("div")
			div2.classList.add("d-flex", "flex-row", "mt-2")
			div2.id = assignGeneralDiv2Id(notification)

			pos_action = document.createElement("a")
			pos_action.classList.add("btn", "btn-primary", "mr-2")
			pos_action.href = "#"
			pos_action.innerHTML = "Accept"
			pos_action.addEventListener("click", function(e){
				e.stopPropagation();
				sendAcceptFriendRequestToSocket(notification['notification_id'])
			})
			pos_action.id = assignGeneralPosActionId(notification)
			div2.appendChild(pos_action)

			neg_action = document.createElement("a")
			neg_action.classList.add("btn", "btn-secondary")
			neg_action.href = "#"
			neg_action.innerHTML = "Decline"
			neg_action.addEventListener("click", function(e){
				e.stopPropagation();
				sendDeclineFriendRequestToSocket(notification['notification_id'])
			})
			neg_action.id = assignGeneralNegActionId(notification)
			div2.appendChild(neg_action)
			card.appendChild(div2)
		}
		// The friend request has been answered (Declined or accepted)
		else{
			var div1 = document.createElement("div")
			div1.classList.add("d-flex", "flex-row", "align-items-start")
			div1.id = assignGeneralDiv1Id(notification)

			img = createGeneralProfileImageThumbnail(notification)
			img.id = assignGeneralImgId(notification)
			div1.appendChild(img)

			span = document.createElement("span")
			span.classList.add("m-auto")
			span.innerHTML = notification['verb']
			span.id = assignGeneralVerbId(notification)
			div1.appendChild(span)
			card.appendChild(div1)
		}
		card.appendChild(createGeneralTimestampElement(notification))

		return card
	}

	/*
		Initialize the general notification menu
		Called when page loads.
	*/
	function setupGeneralNotificationsMenu(){
		var notificationContainer = document.getElementById("id_general_notifications_container")

		if(notificationContainer != null){
			card = createGeneralNotificationCard("id_no_general_notifications")

			var div = document.createElement("div")
			div.classList.add("d-flex", "flex-row", "align-items-start")

			span = document.createElement("span")
			span.classList.add("align-items-start", "pt-1", "m-auto")
			span.innerHTML = "You have no notifications."
			div.appendChild(span)
			card.appendChild(div)
			notificationContainer.appendChild(card)
		}
	}

	/*
		Remove the element that says "There are no notifications".
	*/
	function clearNoGeneralNotificationsCard(){
		var element = document.getElementById("id_no_general_notifications")
		if(element != null && element != "undefined"){
			document.getElementById("id_general_notifications_container").removeChild(element)
		}
	}

	/*
		The card that each notification sits in
	*/
	function createGeneralNotificationCard(cardId){
		var card = document.createElement("div")
		if(cardId != "undefined"){
			card.id = cardId
		}
		card.classList.add("d-flex", "flex-column", "align-items-start", "general-card", "p-4")
		return card
	}

	/*
		Circular image icon that can be in a notification card
	*/
	function createGeneralProfileImageThumbnail(notification){
		var img = document.createElement("img")
		img.classList.add("notification-thumbnail-image", "img-fluid", "rounded-circle", "mr-2")
		img.src = "{% static 'codingwithmitch/dummy_image.png' %}"
		img.id = assignGeneralImgId(notification)
		return img
	}

	/*
		Timestamp at the bottom of each notification card
	*/
	function createGeneralTimestampElement(notification){
		var timestamp = document.createElement("p")
		timestamp.classList.add("small", "pt-2", "timestamp-text")
		timestamp.innerHTML = notification['natural_timestamp']
		timestamp.id = assignGeneralTimestampId(notification)
		return timestamp
	}

</script>

<!-- Send to consumer -->
<script type="text/javascript">
	/*
		Retrieve the first page of notifications.
		Called when page loads.
	*/
	function getFirstGeneralNotificationsPage(){
		if("{{request.user.is_authenticated}}"){
			notificationSocket.send(JSON.stringify({
				"command": "get_general_notifications",
				"page_number": "1",
			}));
		}
	}
</script>

<!-- Helpers for generating IDs -->
<script type="text/javascript">

	function generalRedirect(url){
		window.location.href = url
	}

	function assignGeneralDiv1Id(notification){
		return "id_general_div1_" + notification['notification_id']
	}

	function assignGeneralImgId(notification){
		return "id_general_img_" + notification['notification_id']
	}

	function assignGeneralVerbId(notification){
		return "id_general_verb_" + notification['notification_id']
	}

	function assignGeneralDiv2Id(notification){
		return "id_general_div2_" + notification['notification_id']
	}

	function assignGeneralPosActionId(notification){
		return "id_general_pos_action_" + notification['notification_id']
	}

	function assignGeneralNegActionId(notification){
		return "id_general_neg_action_" + notification['notification_id']
	}

	function assignGeneralTimestampId(notification){
		return "id_timestamp_" + notification['notification_id']
	}

	function assignGeneralCardId(notification){
		return "id_notification_" + notification['notification_id']
	}
</script>

templates/snippets/header.html
{% load static %}

<style type="text/css">
    .chat-dropdown-header:hover {
        cursor: pointer;
        background: var(--main-background-color);
    }

    .chat-dropdown-header {
        color: var(--light-primary-text-color);
    }

    .scrollable-menu {
        height: auto;
        max-height: 90vh;
        width: 500px;
        overflow-x: hidden;
    }
</style>

<!-- Header -->
<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

    <!-- MEDIUM+ SCREENS -->
    <div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
        <h5 class="mr-3 font-weight-normal justify-content-start">
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        </h5>
        <form class="search-bar justify-content-start" onsubmit="return executeQuery();">
            <input type="text" class="form-control" name="q" id="id_q_large" placeholder="Search...">
        </form>

        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav class="">
                {% if request.user.is_authenticated %}
                    <div class="dropdown dropleft show p-2">
                        <div class="d-flex flex-row">

                            <div class="btn-group dropleft">
                                <div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3"
                                     id="id_chat_notification_dropdown_toggle" data-toggle="dropdown">
                                    <span id="id_chat_notifications_count" class="notify-badge"></span>
                                    <span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
                                    <div class="dropdown-menu scrollable-menu"
                                         aria-labelledby="id_chat_notification_dropdown_toggle"
                                         id="id_chat_notifications_container">
                                    </div>
                                </div>
                            </div>

                            <div class="btn-group dropleft">
                                <div class="d-flex notifications-icon-container rounded-circle align-items-center mr-3"
                                     id="id_notification_dropdown_toggle" data-toggle="dropdown"
                                     onclick="setGeneralNotificationsAsRead()">
                                    <span id="id_general_notifications_count" class="notify-badge"></span>
                                    <span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
                                    <div class="dropdown-menu scrollable-menu"
                                         aria-labelledby="id_notification_dropdown_toggle"
                                         id="id_general_notifications_container">
                                    </div>
                                </div>
                            </div>

                            <div class="btn-group dropleft">
                                <img class="account-image rounded-circle m-auto d-block dropdown-toggle"
                                     id="id_profile_links" data-toggle="dropdown" aria-haspopup="true"
                                     aria-expanded="false" src="{{ request.user.profile_image.url }}"
                                     alt="codingwithmitch logo" width="40" height="40">
                                <div class="dropdown-menu" aria-labelledby="id_profile_links">
                                    <a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>

                    </div>
                {% else %}
                    <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
                    <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>
    <!-- END MEDIUM+ SCREENS -->

    <!-- SMALL SCREENS -->
    <div class="d-flex d-md-none flex-column my-auto align-items-center">
        <h5 class="font-weight-normal">
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        </h5>
        <form class="search-bar justify-content-start" onsubmit="return executeQuery();">
            <input type="text" class="form-control" name="q" id="id_q_small" placeholder="Search...">
        </form>
        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav class="">
                {% if request.user.is_authenticated %}
                    <div class="dropdown dropleft p-2 mt-2">
                        <div class="d-flex flex-row">
                            <div class="btn-group dropleft">
                                <img class="account-image rounded-circle m-auto d-block dropdown-toggle"
                                     id="id_profile_links" data-toggle="dropdown" aria-haspopup="true"
                                     aria-expanded="false" src="{{ request.user.profile_image.url }}"
                                     alt="codingwithmitch logo" width="40" height="40">
                                <div class="dropdown-menu" aria-labelledby="id_profile_links">
                                    <a class="dropdown-item" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
                    <a class="btn btn-outline-primary m-2" href="{% url 'register' %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>
    <!-- END SMALL SCREENS -->
</div>


{% include 'snippets/general_notifications.html' %}

<!-- Setup SOCKET for NOTIFICATIONS -->
<script type="text/javascript">
    // Correctly decide between ws:// and wss://
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    // var ws_path = ws_scheme + '://' + window.location.host + ":8001/"; // PRODUCTION
    var ws_path = ws_scheme + '://' + window.location.host + "/";
    // console.log("Connecting to " + ws_path);
    var notificationSocket = new WebSocket(ws_path);

    // Handle incoming messages
    notificationSocket.onmessage = function (message) {
        console.log("Got notification websocket message.");
        var data = JSON.parse(message.data);

        /*
            GENERAL NOTIFICATIONS
        */
        // new 'general' notifications data payload
        if (data.general_msg_type == 0) {
            handleGeneralNotificationsData(data['notifications'], data['new_page_number'])
        }
    }

    notificationSocket.onclose = function (e) {
        console.error('Notification Socket closed unexpectedly');
    };

    notificationSocket.onopen = function (e) {
        console.log("Notification Socket on open: " + e)
        setupGeneralNotificationsMenu()
        getFirstGeneralNotificationsPage()
    }

    notificationSocket.onerror = function (e) {
        console.log('Notification Socket error', e)
    }

    if (notificationSocket.readyState == WebSocket.OPEN) {
        console.log("Notification Socket OPEN complete.")
    } else if (notificationSocket.readyState == WebSocket.CONNECTING) {
        console.log("Notification Socket connecting..")
    }
</script>

<script type="text/javascript">
    setupChatDropdownHeader()

    function executeQuery() {
        var query = ""
        query = document.getElementById('id_q_small').value;
        if (query == "") {
            query = document.getElementById('id_q_large').value;
        }
        window.location.replace("{% url 'search' %}?q=" + query)
        return false
    }

    /*
        Add a header to the dropdown so users can visit /chat/
    */
    function setupChatDropdownHeader() {
        var notificationContainer = document.getElementById("id_chat_notifications_container")

        if (notificationContainer != null) {

            var div = document.createElement("div")
            div.classList.add("chat-dropdown-header", "d-flex", "flex-row", "justify-content-end", "m-auto", "align-items-end")
            div.addEventListener("click", function (e) {
                var url = "{% url 'chat:private-chat-room' %}"
                chatRedirect(url)
            })

            span1 = document.createElement("span")
            span1.classList.add("mr-2")
            span1.innerHTML = "Go to chat"
            div.appendChild(span1)

            span2 = document.createElement("span")
            span2.classList.add("material-icons", "mr-2")
            span2.innerHTML = "open_with"
            div.appendChild(span2)
            notificationContainer.appendChild(div)
        }
    }

    function chatRedirect(url) {
        window.location.href = url
    }

</script>